export const PATH_NAME = {
  HOME: '/',
  CUSTOMER: '/customers',
  EMPLOYEE: '/employees',
  PRODUCT: '/products',
  EVENT: '/events',
  POS: '/pos',
  STOCK: '/stocks',
  LOGIN: '/log-in',
  RESET_PASSWORD: '/reset',
  FORGOT_PASSWORD: '/forgot-password',
  VERIFICATION: '/verification',
  VERIFICATION_SUCCESS: '/verification-success',
  VERIFICATION_ERROR: '/verification-error',
  VERIFICATION_REQUIRED: '/verification-required',
  SETTINGS: '/settings/profile',
}
