name: Development Deployment

on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Linting
        run: npm run lint
      - name: Build
        run: npm run build
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/opt/shop_fe
            pm2 delete shop_fe
            git stash --include-untracked
            git reset --hard
            git clean -fd
            remote_repo="https://${{ secrets.REPO_ACTOR }}:${{ secrets.REPO_TOKEN }}@github.com/${{ secrets.REPO_REPOSITORY }}.git"
            git pull "$remote_repo" dev
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm install
            pm2 start npm --name "shop_fe" -- run start
